# Generated by Django 4.2.7 on 2024-03-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmanagement', '0002_alter_priority_options_alter_slastatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='dependency_reason',
            field=models.TextField(blank=True, verbose_name='Dependency Reason'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reassigned_team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ticketmanagement.reassignedteam', verbose_name='Reassigned Team'),
        ),
    ]
