# Generated by Django 4.2.7 on 2024-03-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmanagement', '0003_alter_incident_dependency_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reassignedteam',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
