# Generated by Django 4.2.7 on 2024-02-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftallowance', '0002_shift_nightshiftcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='team',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('India', 'India')], default='Kenya', max_length=50),
        ),
    ]
