# Generated by Django 4.2.7 on 2024-02-28 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shiftallowance', '0003_shift_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='nightShiftComment',
            field=models.CharField(default='N/A', help_text='eg CRQ NO.', max_length=40, verbose_name='Night Comment'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('team_member', 'shift_type', 'date')},
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.IntegerField()),
                ('team', models.CharField(choices=[('Kenya', 'Kenya'), ('India', 'India')], default='Kenya', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='team',
        ),
    ]
