# Generated by Django 4.2.7 on 2024-03-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftallowance', '0006_onshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onshift',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='onshift',
            name='startDate',
            field=models.DateField(),
        ),
    ]
