# Generated by Django 4.2.7 on 2024-03-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftallowance', '0007_alter_onshift_enddate_alter_onshift_startdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='onShift',
        ),
    ]
